-- 1. USER PROFILES SETUP (Automated sync from auth.users)
-- Create a public profiles table to store user details
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

-- Setup RLS Policies for profiles
create policy "Allow public read access to profiles" on public.profiles
  for select using (true);

create policy "Allow users to update their own profiles" on public.profiles
  for update using (auth.uid() = id);

-- Create trigger function that runs automatically on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a new user is created in auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. STOCK NOTES SETUP (Optional Supabase DB migration)
create table if not exists public.stock_notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  symbol text not null,
  text text default '' not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for stock notes
alter table public.stock_notes enable row level security;

-- Setup RLS Policies for stock notes
create policy "Users can read their own notes" on public.stock_notes
  for select using (auth.uid() = user_id);

create policy "Users can insert their own notes" on public.stock_notes
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own notes" on public.stock_notes
  for update using (auth.uid() = user_id);

create policy "Users can delete their own notes" on public.stock_notes
  for delete using (auth.uid() = user_id);

-- Create a unique index for (user_id, symbol) to upsert notes
create unique index if not exists stock_notes_user_symbol_idx on public.stock_notes (user_id, symbol);


-- 3. PORTFOLIO HOLDINGS SETUP (Optional Supabase DB migration)
create table if not exists public.holdings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  symbol text not null,
  qty numeric not null check (qty >= 0),
  avg_price numeric not null check (avg_price >= 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for holdings
alter table public.holdings enable row level security;

-- Setup RLS Policies for holdings
create policy "Users can view their own holdings" on public.holdings
  for select using (auth.uid() = user_id);

create policy "Users can add holdings" on public.holdings
  for insert with check (auth.uid() = user_id);

create policy "Users can update holdings" on public.holdings
  for update using (auth.uid() = user_id);

create policy "Users can delete holdings" on public.holdings
  for delete using (auth.uid() = user_id);

-- Create a unique index for (user_id, symbol) to prevent duplicates
create unique index if not exists holdings_user_symbol_idx on public.holdings (user_id, symbol);
